# Config

Sound:
  Sell: "ENTITY_EXPERIENCE_ORB_PICKUP"
  Error: "ENTITY_VILLAGER_NO"


Log sell with sell wand in console: false

# Should we destroy wand when is got 0 use?
Destroy wand: true

Hologram line:
  - "&6Item amount to sell in chest &e%amount% &6items."
  - "&6For a total of &e%price%"

# After how many seconds hologram will be removed
Hologram time: 5

# Confirmation for sale with double click
Confirmation:
  enabled: true
  # Particle color. RGB format (red, green, blue)
  color: "0,255,0"
  # How many seconds player have to confirm sell
  time: 2

system:
  # What locale should we use?
  locale: "en_US"